server:
  port: 8091
spring:
  application:
    name: register-center
eureka:
  client:
    service-url:
      defaultZone: http://server1:8080/eureka
    fetch-registry: true
  instance:
    hostname: server2